"""Generate the D-number table of contents for ``charter/decisions.md``.

The ToC lists every decision once as ``D<n> — <short title> — L<line>``, where
``<line>`` is the 1-based line of that decision's canonical entry in the
committed file. It is emitted between the idempotent sentinel markers
``<!-- TOC:START -->`` / ``<!-- TOC:END -->`` so regeneration produces no diff
on an unchanged file.

Run at the close of any session that adds or moves a D-entry::

    python -m ops.decisions_toc            # rewrites the ToC in place
    python -m ops.decisions_toc --check    # exits non-zero if a rewrite is due

A decision entry is any line that opens with the bold ``D<n>`` token, whether a
Phase-1 summary bullet (``- **D<n>: ...``) in the upper block or a full-content
Phase-2 entry (``**D<n>: ...`` or ``**D<n> — ...``). Line numbers drift when
entries are added or moved, which is exactly why the ToC is regenerated rather
than hand-maintained; the markers keep regeneration mechanical and idempotent.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

DECISIONS = Path(__file__).resolve().parents[1] / "charter" / "decisions.md"

START = "<!-- TOC:START -->"
END = "<!-- TOC:END -->"
NOTE = (
    "<!-- Generated by ops/decisions_toc.py — do not hand-edit; regenerate "
    "(`python -m ops.decisions_toc`) whenever a D-entry is added or moved. -->"
)
FENCE = "```text"

ENTRY_RE = re.compile(r"^(?:- )?\*\*D(\d+)(?:: | — )(.*?)\*\*")
TITLE_CAP = 70


def _short_title(raw: str) -> str:
    title = raw.strip().rstrip(".").strip()
    if len(title) <= TITLE_CAP:
        return title
    cut = title[:TITLE_CAP].rsplit(" ", 1)[0]
    return f"{cut}…"


def render(text: str) -> str:
    """Return ``text`` with the ToC block regenerated between the sentinels."""
    lines = text.split("\n")
    try:
        start = lines.index(START)
        end = lines.index(END)
    except ValueError as exc:  # pragma: no cover - sentinels are committed
        raise SystemExit(
            f"sentinel markers {START} / {END} not found in {DECISIONS}"
        ) from exc

    base = lines[:start] + lines[end + 1:]
    ip = start  # insertion index within `base`

    entries = []  # (num, title, base_index)
    for i, ln in enumerate(base):
        m = ENTRY_RE.match(ln)
        if m:
            entries.append((int(m.group(1)), _short_title(m.group(2)), i))

    n = len(entries)
    pre = [START, NOTE, FENCE]
    post = ["```", END]
    height = len(pre) + n + len(post)

    toc = list(pre)
    for num, title, base_index in entries:
        line_no = base_index + 1 + height  # all entries sit below the ToC
        toc.append(f"D{num} — {title} — L{line_no}")
    toc += post

    new_lines = base[:ip] + toc + base[ip:]
    return "\n".join(new_lines)


def main(argv: list[str]) -> int:
    text = DECISIONS.read_text()
    # normalise to no trailing blank lines so reformatting stays stable
    body = text.rstrip("\n")
    regenerated = render(body) + "\n"
    if "--check" in argv:
        if regenerated != text:
            print("decisions.md ToC is stale — run `python -m ops.decisions_toc`")
            return 1
        print("decisions.md ToC is up to date")
        return 0
    DECISIONS.write_text(regenerated)
    n = sum(1 for ln in regenerated.split("\n") if ENTRY_RE.match(ln))
    print(f"regenerated ToC: {n} decisions")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
